version: "3.7"
services: 
  db:
    image: mysql
    container_name: mysql-container
    command: --default-authentication-plugin=mysql_native_password
    environment: 
      MYSQL_ROOT_PASSWORD: devjg
    volumes:
      - ./server/db/data:/var/lib/mysql
    restart: always
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-container
    environment:
      MYSQL_ROOT_PASSWORD: devjg
    ports:
      - "8080:80"
    volumes:
      - ./server/phpmyadmin/uploads.ini:/usr/local/etc/php/conf.d/php-phpmyadmin.ini
    depends_on: 
      - db
  web:
    image: webdevops/php-apache:alpine-php7
    container_name: php-container
    restart: always
    volumes:
      - ./www:/app
    ports:
      - "8888:80"
    links:
      - db